"""

Revision ID: 1644f4a001ec
Revises:
Create Date: 2026-05-14 22:18:55.100829

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1644f4a001ec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("codeforces_api_key", sa.String(length=100), nullable=True),
        sa.Column("codeforces_api_secret", sa.String(length=100), nullable=True),
        sa.Column("polygon_api_key", sa.String(length=100), nullable=True),
        sa.Column("polygon_api_secret", sa.String(length=100), nullable=True),
        sa.Column("yandex_access_token", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "ai_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("history", sa.JSON(), nullable=False),
        sa.Column("statement", sa.JSON(), nullable=True),
        sa.Column("progress", sa.JSON(), nullable=True),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("polygon_problem_id", sa.Integer(), nullable=True),
        sa.Column("package_id", sa.Integer(), nullable=True),
        sa.Column("upload_errors", sa.JSON(), nullable=True),
        sa.Column("ai_fix_attempts", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_sessions_id"), "ai_sessions", ["id"], unique=False)
    op.create_table(
        "contests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(length=100), nullable=False),
        sa.Column("external_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=5), nullable=False),
        sa.Column("unofficial", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("duration", sa.Interval(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("refresh_hash", sa.String(length=256), nullable=False),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_in", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_hash"),
    )
    op.create_table(
        "ai_generated_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("uploaded", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["ai_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contest_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["participant_id"],
            ["participants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "plagiarism_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("only_ok", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=100), nullable=True),
        sa.Column("full_name", sa.String(length=500), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contest_participant_id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("tries_count", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("last_success_time", sa.DateTime(), nullable=True),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_participant_id"],
            ["contest_participants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("task_result_id", sa.Integer(), nullable=False),
        sa.Column("participant_login", sa.String(length=255), nullable=False),
        sa.Column("task_name", sa.String(length=500), nullable=False),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("run_time", sa.Interval(), nullable=False),
        sa.Column("memory_bytes", sa.Integer(), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_result_id"],
            ["task_results.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pair_of_banned_submissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("contest_id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("first_submission_id", sa.String(), nullable=False),
        sa.Column("second_submission_id", sa.String(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["contest_id"],
            ["contests.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_submission_id"],
            ["submissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["plagiarism_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_submission_id"],
            ["submissions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pair_of_banned_submissions")
    op.drop_table("submissions")
    op.drop_table("task_results")
    op.drop_table("tasks")
    op.drop_table("plagiarism_reports")
    op.drop_table("contest_participants")
    op.drop_table("ai_generated_files")
    op.drop_table("refresh_tokens")
    op.drop_table("participants")
    op.drop_table("contests")
    op.drop_index(op.f("ix_ai_sessions_id"), table_name="ai_sessions")
    op.drop_table("ai_sessions")
    op.drop_table("users")
    op.drop_table("roles")
    # ### end Alembic commands ###
