"""

Revision ID: 444be839825c
Revises: 3f1fdec7d630
Create Date: 2026-04-22 00:49:26.953663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '444be839825c'
down_revision: Union[str, Sequence[str], None] = '3f1fdec7d630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('memory_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'memory_bytes')
    # ### end Alembic commands ###
