"""

Revision ID: 4cfea7bf1906
Revises: 13d0ccb1e8d6
Create Date: 2026-04-23 08:30:35.665599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfea7bf1906'
down_revision: Union[str, Sequence[str], None] = '13d0ccb1e8d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plagiarism_reports', sa.Column('only_ok', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plagiarism_reports', 'only_ok')
    # ### end Alembic commands ###
