"""

Revision ID: 579596ae2e6a
Revises: 12f56568cd5b
Create Date: 2026-06-03 06:22:38.196581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579596ae2e6a'
down_revision: Union[str, Sequence[str], None] = '12f56568cd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polygon_problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('polygon_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('favourite', sa.Boolean(), nullable=False),
    sa.Column('access_type', sa.String(length=16), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('working_copy_revision', sa.Integer(), nullable=True),
    sa.Column('latest_package', sa.Integer(), nullable=True),
    sa.Column('modified', sa.Boolean(), nullable=False),
    sa.Column('input_file', sa.String(length=255), nullable=True),
    sa.Column('output_file', sa.String(length=255), nullable=True),
    sa.Column('interactive', sa.Boolean(), nullable=False),
    sa.Column('well_formed', sa.Boolean(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=True),
    sa.Column('memory_limit', sa.Integer(), nullable=True),
    sa.Column('list_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('info_fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'polygon_id', name='uq_polygon_problems_user_polygon')
    )
    op.create_index(op.f('ix_polygon_problems_id'), 'polygon_problems', ['id'], unique=False)
    op.create_index(op.f('ix_polygon_problems_polygon_id'), 'polygon_problems', ['polygon_id'], unique=False)
    op.create_index(op.f('ix_polygon_problems_user_id'), 'polygon_problems', ['user_id'], unique=False)
    op.create_table('polygon_checkers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polygon_checkers_problem_id'), 'polygon_checkers', ['problem_id'], unique=True)
    op.create_table('polygon_generators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'name', name='uq_polygon_generators_problem_name')
    )
    op.create_index(op.f('ix_polygon_generators_problem_id'), 'polygon_generators', ['problem_id'], unique=False)
    op.create_table('polygon_scripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('testset', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'testset', name='uq_polygon_scripts_problem_testset')
    )
    op.create_index(op.f('ix_polygon_scripts_problem_id'), 'polygon_scripts', ['problem_id'], unique=False)
    op.create_table('polygon_solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=8), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'name', name='uq_polygon_solutions_problem_name')
    )
    op.create_index(op.f('ix_polygon_solutions_problem_id'), 'polygon_solutions', ['problem_id'], unique=False)
    op.create_table('polygon_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('legend', sa.Text(), nullable=True),
    sa.Column('input', sa.Text(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('scoring', sa.Text(), nullable=True),
    sa.Column('interaction', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tutorial', sa.Text(), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'lang', name='uq_polygon_statements_problem_lang')
    )
    op.create_index(op.f('ix_polygon_statements_problem_id'), 'polygon_statements', ['problem_id'], unique=False)
    op.create_table('polygon_test_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('testset', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('points_policy', sa.String(length=32), nullable=True),
    sa.Column('feedback_policy', sa.String(length=32), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'testset', 'name', name='uq_polygon_test_groups_problem_testset_name')
    )
    op.create_index(op.f('ix_polygon_test_groups_problem_id'), 'polygon_test_groups', ['problem_id'], unique=False)
    op.create_table('polygon_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('testset', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('input_b64', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=128), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('use_in_statements', sa.Boolean(), nullable=False),
    sa.Column('input_for_statements', sa.Text(), nullable=True),
    sa.Column('output_for_statements', sa.Text(), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_id', 'testset', 'index', name='uq_polygon_tests_problem_testset_index')
    )
    op.create_index(op.f('ix_polygon_tests_problem_id'), 'polygon_tests', ['problem_id'], unique=False)
    op.create_table('polygon_validators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=True),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['polygon_problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_polygon_validators_problem_id'), 'polygon_validators', ['problem_id'], unique=True)
    op.create_index(op.f('ix_ai_generated_files_session_id'), 'ai_generated_files', ['session_id'], unique=False)
    op.add_column('ai_sessions', sa.Column('cached_polygon_problem_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ai_sessions_user_id'), 'ai_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'ai_sessions', 'polygon_problems', ['cached_polygon_problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_sessions', type_='foreignkey')  # type: ignore[arg-type]
    op.drop_index(op.f('ix_ai_sessions_user_id'), table_name='ai_sessions')
    op.drop_column('ai_sessions', 'cached_polygon_problem_id')
    op.drop_index(op.f('ix_ai_generated_files_session_id'), table_name='ai_generated_files')
    op.drop_index(op.f('ix_polygon_validators_problem_id'), table_name='polygon_validators')
    op.drop_table('polygon_validators')
    op.drop_index(op.f('ix_polygon_tests_problem_id'), table_name='polygon_tests')
    op.drop_table('polygon_tests')
    op.drop_index(op.f('ix_polygon_test_groups_problem_id'), table_name='polygon_test_groups')
    op.drop_table('polygon_test_groups')
    op.drop_index(op.f('ix_polygon_statements_problem_id'), table_name='polygon_statements')
    op.drop_table('polygon_statements')
    op.drop_index(op.f('ix_polygon_solutions_problem_id'), table_name='polygon_solutions')
    op.drop_table('polygon_solutions')
    op.drop_index(op.f('ix_polygon_scripts_problem_id'), table_name='polygon_scripts')
    op.drop_table('polygon_scripts')
    op.drop_index(op.f('ix_polygon_generators_problem_id'), table_name='polygon_generators')
    op.drop_table('polygon_generators')
    op.drop_index(op.f('ix_polygon_checkers_problem_id'), table_name='polygon_checkers')
    op.drop_table('polygon_checkers')
    op.drop_index(op.f('ix_polygon_problems_user_id'), table_name='polygon_problems')
    op.drop_index(op.f('ix_polygon_problems_polygon_id'), table_name='polygon_problems')
    op.drop_index(op.f('ix_polygon_problems_id'), table_name='polygon_problems')
    op.drop_table('polygon_problems')
    # ### end Alembic commands ###
