"""

Revision ID: 7f17656a3690
Revises: 
Create Date: 2025-12-15 19:31:28.326835

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f17656a3690"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contest_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("type", sa.String(length=5), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=True),
        sa.Column("finish_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pairs_of_banned_submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("rating", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("refresh_token", sa.String(length=256), nullable=False),
        sa.Column("expires_in", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token"),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "submissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("send_time", sa.DateTime(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("run_time", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=100000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("tries_count", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(length=50), nullable=False),
        sa.Column("last_success_time", sa.DateTime(), nullable=True),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("short_name", sa.String(length=20), nullable=True),
        sa.Column("full_name", sa.String(length=100), nullable=False),
        sa.Column("max_score", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("login", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=False),
        sa.Column("codeforces_api_key", sa.String(length=100), nullable=True),
        sa.Column("codeforces_api_secret", sa.String(length=100), nullable=True),
        sa.Column("yandex_access_token", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("login"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("tasks")
    op.drop_table("task_results")
    op.drop_table("submissions")
    op.drop_table("roles")
    op.drop_table("refresh_tokens")
    op.drop_table("participants")
    op.drop_table("pairs_of_banned_submissions")
    op.drop_table("contests")
    op.drop_table("contest_participants")
    # ### end Alembic commands ###
