"""Delete tests of a Polygon problem testset."""

from sqlalchemy.ext.asyncio import AsyncSession

from api.user.polygon.client import get_user, polygon_call


async def delete_tests(
    problem_id: int,
    testset: str,
    test_indices: list[int],
    user_id: int,
    db: AsyncSession,
):
    """Delete the given tests via problem.deleteTest.

    Polygon pre-checks every requested test first and deletes nothing if any of
    them fails the check (e.g. a test generated by the script), so a refusal
    leaves the testset untouched.
    """
    user = await get_user(user_id, db)
    return await polygon_call(
        "problem.deleteTest",
        {
            "problemId": str(problem_id),
            "testset": testset,
            "testIndices": ",".join(str(i) for i in test_indices),
        },
        user,
    )
