"""Shared prompt fragments reused across the per-file-type prompts.

Each technical file is generated by its own dedicated prompt module (validator,
generator, checker, ...) so the model focuses on one artifact at a time. Those
modules compose the fragments below to avoid duplicating the long, stable
instructions (LaTeX rules, the Freemarker tutorial, the testlib references).

``ASCII_CODE_RULE`` forces ASCII-only comments/literals in generated source
because Cyrillic breaks Polygon's file encoding: Polygon stores files as cp1251,
which then fails to decode as UTF-8.
"""

LATEX_FORMATTING = (
    "ФОРМАТИРОВАНИЕ — ТОЛЬКО LaTeX, никакого Markdown. Polygon рендерит в HTML "
    "лишь ОГРАНИЧЕННЫЙ набор команд — используй СТРОГО ТОЛЬКО их, любые другие "
    "(\\begin{verbatim}, \\section, \\\\ вне таблиц, markdown ``` и т.п.) ЗАПРЕЩЕНЫ:\n"
    "- жирный: \\textbf{...}; курсив: \\textit{...}; зачёркнутый: \\sout{...}; "
    "капитель: \\textsc{...}\n"
    "- моноширинный inline: \\texttt{...}; если внутри спецсимволы — \\verb|...|. "
    "НЕ `текст`\n"
    "- математика: $формула$ (внутри строки) или $$формула$$ (по центру отдельной строкой). "
    "Внутри $...$ можно любые математические команды LaTeX\n"
    "- БЛОК кода на несколько строк: \\begin{lstlisting} ... \\end{lstlisting} "
    "(подсветка синтаксиса). НИКОГДА не используй \\begin{verbatim} и markdown-блоки ```\n"
    "- списки: \\begin{itemize}\\item ...\\end{itemize} или \\begin{enumerate}\\item ...; "
    "НЕ markdown-списки (- item)\n"
    "- таблицы: \\begin{tabular}{|c|c|} ... \\\\ \\hline ... \\end{tabular}\n"
    "- по центру: \\begin{center} ... \\end{center}; размеры: \\small, \\large; "
    "ссылки: \\href{url}{текст}\n"
    "- кавычки-ёлочки: <<...>>; длинное тире: ---\n"
    "Не вставляй длинные листинги исходного кода в legend без явной просьбы "
    "пользователя — условие должно оставаться чистым и читаемым."
)

NO_FENCES = (
    "КРИТИЧЕСКИ ВАЖНО: верни ТОЛЬКО чистый исходный код файла. "
    "НЕ оборачивай код в markdown (никаких ```cpp, ```, ~~~ и т.п.), "
    "без пояснений до или после кода."
)

ASCII_CODE_RULE = (
    "ВАЖНО: ВСЕ комментарии и строковые литералы в коде пиши ТОЛЬКО на английском "
    "языке (ASCII). НЕ используй кириллицу внутри кода — иначе ломается кодировка "
    "файла на Polygon."
)

TESTLIB_INTRO = (
    "Ты — эксперт по testlib.h и разработке задач для спортивного программирования. "
    "Полезные ресурсы: "
    "https://codeforces.com/blog/entry/18289 (testlib), "
    "https://codeforces.com/blog/entry/18291 (генерация тестов), "
    "https://codeforces.com/blog/entry/18426 (валидаторы), "
    "https://codeforces.com/blog/entry/18431 (чекеры), "
    "https://codeforces.com/blog/entry/18455 (интерактивные задачи). "
    'Подключай testlib через #include "testlib.h".'
)

INCORRECT_SOLUTION_RULES = (
    "ПРАВИЛА ДЛЯ НЕКОРРЕКТНЫХ РЕШЕНИЙ (ОБЯЗАТЕЛЬНО СОБЛЮДАТЬ):"
    "\n- TL: Напиши ПРАВИЛЬНОЕ решение задачи, но используй заведомо медленный алгоритм — "
    "вложенные циклы O(n²) или O(n³) там, где возможен O(n log n) или O(n). "
    "Например: сортировка пузырьком, перебор всех пар, полный перебор подмножеств. "
    "ЗАПРЕЩЕНО: sleep(), busy-loop, искусственные задержки. "
    "Результат должен быть ВЕРНЫМ на малых тестах, но превышать TL на больших."
    "\n- ML: Напиши ПРАВИЛЬНОЕ решение задачи, но с избыточным расходом памяти — "
    "используй O(n²) памяти там, где достаточно O(n). "
    "Например: храни всю матрицу пар вместо одномерного массива, "
    "или создавай n копий входного массива, или используй map/set с парами. "
    "ЗАПРЕЩЕНО: new int[1000000000], искусственное выделение памяти не по алгоритму. "
    "Результат должен быть ВЕРНЫМ на малых тестах, но превышать ML на больших."
    "\n- WA: Напиши НЕВЕРНОЕ решение — алгоритм с правдоподобной, но ошибочной логикой. "
    "Например: жадный алгоритм там, где нужна DP; игнорирование граничных случаев; "
    "неверная формула для подсчёта. Решение должно давать WA хотя бы на части тестов."
    "\n- RE: Напиши решение, которое вызовет Runtime Error на некоторых тестах — "
    "например, обращение к вектору по индексу без проверки границ, "
    "деление на ноль при определённых входных данных, "
    "stack overflow от рекурсии без базового случая."
)

FREEMARKER_TUTORIAL = (
    "Правила использования script для генерации тестов в Polygon: "
    "Freemarker Template Engine is an engine, created to process text files. "
    "It process only parts of text files, that are surrounded with special Freemarker directives. "
    "Everything else is copied directly to the output. "
    "So if the file does not contain Freemarker at all, "
    "that the result of the processing such file is an exact copy of this file."
    "Input:"
    "gen 100 100 1 > 1"
    "gen 100 100 2 > 2"
    "gen 100 100 3 > 3"
    "gen 100 100 4 > 4"
    "Output:"
    "gen 100 100 1 > 1"
    "gen 100 100 2 > 2"
    "gen 100 100 3 > 3"
    "gen 100 100 4 > 4"
    "Variables are created automatically during their first assignment. "
    "To assign a value to the variable #assign directive is used."
    "<#assign i = 10/>"
    "To evaluate some expression with variables you should enclose it in ${} symbols."
    "<#assign i = 10/>"
    "gen ${i} ${i*2 + 1} ${i*i + 10} > $"
    "Input:"
    "<#assign i = 2/>"
    "<#assign j = 3/>"
    "gen ${i} ${j} ${i + j} ${i*j + i + j + 2} > $"
    "<#assign i2 = i*i/>"
    "<#assign j2 = j*j/>"
    "gen ${i2} ${j2} > $"
    "Output:"
    "gen 2 3 5 13 > $"
    "gen 4 9 > $"
    "To iterate through the range of integers, #list directive is used."
    "<#list 10..20 as iter></#list>"
    "For example:"
    "<#list 10..20 as iter>"
    "gen 100 200 ${iter*iter + 10} > $"
    "</#list>"
    "Of course, loops can be nested. And all variables, that were declared previously, "
    "can be used inside."
    "Input:"
    "<#assign maxN = 1/>"
    "<#list 1..5 as power>"
    "<#assign maxN = maxN * 10>"
    "<#list 1..5 as testNumber>"
    "generatorFile ${maxN} abacaba ${testNumber} > $"
    "</#list>"
    "</#list>"
    "Output:"
    "generatorFile 10 abacaba 1 > $"
    "generatorFile 100 abacaba 1 > $"
    "generatorFile 1000 abacaba 1 > $"
    "For more detailed tutorial please see Freemarker Documentation. "
    "Мы пишем файл generator.cpp, поэтому и вызывать должны генерацию тестов через generator. "
    "Учитывай, что нельзя использовать одинаковые скрипты для генерации разных тестов, "
    "необходимо хотя бы создать фиктивную переменную, которая будет отличать эти тесты. "
    "Внимательно проверяй, чтобы в скрипте любая пара тестов отличалась хотя бы фиктивной переменной. "
    "Если ты создаёшь фиктивную переменную, которая не влияет на генерацию тестов, "
    "то её всё равно по правилам полигона нужно использовать в генераторе тестов "
    "(можно просто объявить её в коде). "
    "Параметры скрипта можно использовать для генерации тестов: "
    "если в условии есть ограничения на n, используй их в скрипте. "
    "Сделай тесты максимально разнообразными, чтобы покрыть все возможные случаи. "
    "Скрипт должен генерировать тесты, соответствующие условию и не выходящие за рамки ограничений."
)
