"""Shared prompt fragments reused across the per-file-type prompts.

Each technical file is generated by its own dedicated prompt module (validator,
generator, checker, ...) so the model focuses on one artifact at a time. Those
modules compose the fragments below to avoid duplicating the long, stable
instructions (LaTeX rules, the Freemarker tutorial, the testlib references).

``ASCII_CODE_RULE`` forces ASCII-only comments/literals in generated source
because Cyrillic breaks Polygon's file encoding: Polygon stores files as cp1251,
which then fails to decode as UTF-8.
"""

LATEX_FORMATTING = (
    "ФОРМАТИРОВАНИЕ — ТОЛЬКО LaTeX, никакого Markdown. Polygon рендерит в HTML "
    "лишь ОГРАНИЧЕННЫЙ набор команд — используй СТРОГО ТОЛЬКО их, любые другие "
    "(\\begin{verbatim}, \\section, \\\\ вне таблиц, markdown ``` и т.п.) ЗАПРЕЩЕНЫ:\n"
    "- жирный: \\textbf{...}; курсив: \\textit{...}; зачёркнутый: \\sout{...}; "
    "капитель: \\textsc{...}\n"
    "- моноширинный inline: \\texttt{...}; если внутри спецсимволы — \\verb|...|. "
    "НЕ `текст`\n"
    "- математика: $формула$ (внутри строки) или $$формула$$ (по центру отдельной строкой). "
    "Внутри $...$ можно любые математические команды LaTeX\n"
    "- БЛОК кода на несколько строк: \\begin{lstlisting} ... \\end{lstlisting} "
    "(подсветка синтаксиса). НИКОГДА не используй \\begin{verbatim} и markdown-блоки ```\n"
    "- списки: \\begin{itemize}\\item ...\\end{itemize} или \\begin{enumerate}\\item ...; "
    "НЕ markdown-списки (- item)\n"
    "- таблицы: \\begin{tabular}{|c|c|} ... \\\\ \\hline ... \\end{tabular}\n"
    "- по центру: \\begin{center} ... \\end{center}; размеры: \\small, \\large; "
    "ссылки: \\href{url}{текст}\n"
    "- кавычки-ёлочки: <<...>>; длинное тире: ---\n"
    "Не вставляй длинные листинги исходного кода в legend без явной просьбы "
    "пользователя — условие должно оставаться чистым и читаемым."
)

NO_FENCES = (
    "КРИТИЧЕСКИ ВАЖНО: верни ТОЛЬКО чистый исходный код файла. "
    "НЕ оборачивай код в markdown (никаких ```cpp, ```, ~~~ и т.п.), "
    "без пояснений до или после кода."
)

ASCII_CODE_RULE = (
    "ВАЖНО: ВСЕ комментарии и строковые литералы в коде пиши ТОЛЬКО на английском "
    "языке (ASCII). НЕ используй кириллицу внутри кода — иначе ломается кодировка "
    "файла на Polygon."
)

TESTLIB_INTRO = (
    "Ты — эксперт по testlib.h и разработке задач для спортивного программирования. "
    "Полезные ресурсы: "
    "https://codeforces.com/blog/entry/18289 (testlib), "
    "https://codeforces.com/blog/entry/18291 (генерация тестов), "
    "https://codeforces.com/blog/entry/18426 (валидаторы), "
    "https://codeforces.com/blog/entry/18431 (чекеры), "
    "https://codeforces.com/blog/entry/18455 (интерактивные задачи). "
    'Подключай testlib через #include "testlib.h".'
)

# A generator must never fabricate an unreliable incorrect solution. When it
# cannot honestly guarantee the tagged verdict with a genuine algorithm, it emits
# this exact marker (optionally followed by a short reason) INSTEAD of code; the
# caller then skips that solution and tells the user why, rather than uploading a
# solution that will fail Polygon's tag verification and churn the repair loop.
SKIP_MARKER = "SKIP"

INCORRECT_SOLUTION_RULES = (
    "ПРАВИЛА ДЛЯ РЕШЕНИЙ С НАМЕРЕННЫМ ВЕРДИКТОМ (ТЕГ = ОЖИДАЕМЫЙ ВЕРДИКТ):\n"
    "Polygon при сборке ПРОВЕРЯЕТ, что решение реально получает СВОЙ вердикт. Если "
    "решение с тегом TL получит WA (или наоборот) — пакет не соберётся. Поэтому решение "
    "должно получать РОВНО свой вердикт настоящим алгоритмом.\n"
    "ИСПОЛЬЗУЙ ТОЛЬКО НАСТОЯЩИЕ АЛГОРИТМЫ, а не искусственные трюки. КАТЕГОРИЧЕСКИ "
    "ЗАПРЕЩЕНО: бесконечные циклы, `while(true)`, sleep/busy-loop, искусственные задержки, "
    "`assert(false)`/`abort()`/намеренный краш, выделение памяти не по алгоритму "
    "(`new int[1e9]`). Вердикт должен возникать ЕСТЕСТВЕННО из сложности/логики алгоритма.\n"
    "- TL: правильный по ответам, но заведомо слишком медленный алгоритм для старших "
    "ограничений: перебор всех перестановок O(n!) / подмножеств O(2^n) / O(n^2)-O(n^3) там, "
    "где нужен O(n log n)/O(n). На малых входах даёт ВЕРНЫЙ ответ (OK), на больших — не "
    "успевает (TL). НИКАКИХ пустых циклов — только реальные вычисления.\n"
    "- ML: правильный по ответам алгоритм, но с избыточной памятью по самой структуре "
    "(например матрица O(n^2) вместо O(n), мемоизация по парам). На больших входах "
    "естественно превышает память (ML).\n"
    "- WA: правдоподобный, но неверный алгоритм (жадность вместо ДП, неверная формула, "
    "игнор граничного случая). Вывод ПРАВИЛЬНОГО ФОРМАТА, но неверный по значению хотя бы "
    "на части тестов (чтобы был WA, а не PE/RE).\n"
    "- RE: решение, которое на части тестов ЕСТЕСТВЕННО падает (например переполнение "
    "стека глубокой рекурсией, обращение за границу массива на больших индексах), но не "
    "через намеренный краш.\n"
    "ЕСЛИ ты НЕ можешь честно ГАРАНТИРОВАТЬ нужный вердикт настоящим алгоритмом для этой "
    f"задачи — НЕ выдумывай решение. Верни РОВНО одну строку: `{SKIP_MARKER}: <краткая "
    "причина на русском>` (например почему нельзя надёжно получить TL/ML/RE именно здесь). "
    "Лучше не добавить решение, чем добавить решение с неверным вердиктом."
)

FREEMARKER_TUTORIAL = (
    "Правила использования script для генерации тестов в Polygon: "
    "Freemarker Template Engine is an engine, created to process text files. "
    "It process only parts of text files, that are surrounded with special Freemarker directives. "
    "Everything else is copied directly to the output. "
    "So if the file does not contain Freemarker at all, "
    "that the result of the processing such file is an exact copy of this file."
    "Input:"
    "gen 100 100 1 > 1"
    "gen 100 100 2 > 2"
    "gen 100 100 3 > 3"
    "gen 100 100 4 > 4"
    "Output:"
    "gen 100 100 1 > 1"
    "gen 100 100 2 > 2"
    "gen 100 100 3 > 3"
    "gen 100 100 4 > 4"
    "Variables are created automatically during their first assignment. "
    "To assign a value to the variable #assign directive is used."
    "<#assign i = 10/>"
    "To evaluate some expression with variables you should enclose it in ${} symbols."
    "<#assign i = 10/>"
    "gen ${i} ${i*2 + 1} ${i*i + 10} > $"
    "Input:"
    "<#assign i = 2/>"
    "<#assign j = 3/>"
    "gen ${i} ${j} ${i + j} ${i*j + i + j + 2} > $"
    "<#assign i2 = i*i/>"
    "<#assign j2 = j*j/>"
    "gen ${i2} ${j2} > $"
    "Output:"
    "gen 2 3 5 13 > $"
    "gen 4 9 > $"
    "To iterate through the range of integers, #list directive is used."
    "<#list 10..20 as iter></#list>"
    "For example:"
    "<#list 10..20 as iter>"
    "gen 100 200 ${iter*iter + 10} > $"
    "</#list>"
    "Of course, loops can be nested. And all variables, that were declared previously, "
    "can be used inside."
    "Input:"
    "<#assign maxN = 1/>"
    "<#list 1..5 as power>"
    "<#assign maxN = maxN * 10>"
    "<#list 1..5 as testNumber>"
    "generatorFile ${maxN} abacaba ${testNumber} > $"
    "</#list>"
    "</#list>"
    "Output:"
    "generatorFile 10 abacaba 1 > $"
    "generatorFile 100 abacaba 1 > $"
    "generatorFile 1000 abacaba 1 > $"
    "For more detailed tutorial please see Freemarker Documentation. "
    "Мы пишем файл generator.cpp, поэтому и вызывать должны генерацию тестов через generator. "
    "Учитывай, что нельзя использовать одинаковые скрипты для генерации разных тестов, "
    "необходимо хотя бы создать фиктивную переменную, которая будет отличать эти тесты. "
    "Внимательно проверяй, чтобы в скрипте любая пара тестов отличалась хотя бы фиктивной переменной. "
    "Если ты создаёшь фиктивную переменную, которая не влияет на генерацию тестов, "
    "то её всё равно по правилам полигона нужно использовать в генераторе тестов "
    "(можно просто объявить её в коде). "
    "Параметры скрипта можно использовать для генерации тестов: "
    "если в условии есть ограничения на n, используй их в скрипте. "
    "Сделай тесты максимально разнообразными, чтобы покрыть все возможные случаи. "
    "Скрипт должен генерировать тесты, соответствующие условию и не выходящие за рамки ограничений."
)
