name: "CI Workflow"

on:
  pull_request:
    branches: [ main ]

env:
  CODEFORCES_TEST_KEY: ${{ secrets.CODEFORCES_TEST_KEY }}
  CODEFORCES_TEST_SECRET: ${{ secrets.CODEFORCES_TEST_SECRET }}
  CODEFORCES_HOST: ${{ secrets.CODEFORCES_HOST }}

  YANDEX_CLIENT_ID: ${{ secrets.YANDEX_CLIENT_ID }}
  YANDEX_CLIENT_SECRET: ${{ secrets.YANDEX_CLIENT_SECRET }}
  YANDEX_HOST: ${{ secrets.YANDEX_HOST }}
  YANDEX_TEST_OAUTH: ${{ secrets.YANDEX_TEST_OAUTH }}

  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run make build
        run: |
          pip install --upgrade pip
          make build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make lint
        run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run make test
        run: make test
